# Generated by Django 3.2.21 on 2023-09-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230910_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='usr',
            new_name='user',
        ),
    ]
